import type { CurriculumTopic, CurriculumUnitCode } from "./types";

/** Pearson Edexcel International Advanced Level Economics (YEC11 pathway) — topic map for classroom use (not an official publication). */
export const CURRICULUM_UNITS: Record<
  CurriculumUnitCode,
  { code: CurriculumUnitCode; title: string }
> = {
  WEC11: {
    code: "WEC11",
    title: "Unit 1 — Markets in action",
  },
  WEC12: {
    code: "WEC12",
    title: "Unit 2 — Macroeconomic performance and policy",
  },
  WEC13: {
    code: "WEC13",
    title: "Unit 3 — Business behaviour",
  },
  WEC14: {
    code: "WEC14",
    title: "Unit 4 — Developments in the global economy",
  },
};

export const CURRICULUM_TOPICS: CurriculumTopic[] = [
  {
    unitCode: "WEC11",
    unitTitle: CURRICULUM_UNITS.WEC11.title,
    topicCode: "1.1",
    topicTitle: "Scarcity, choice, and economic systems",
    specKeywords: [
      "opportunity cost",
      "ppf",
      "production possibility",
      "mixed economy",
      "market",
      "command",
    ],
  },
  {
    unitCode: "WEC11",
    unitTitle: CURRICULUM_UNITS.WEC11.title,
    topicCode: "1.2",
    topicTitle: "Demand, supply, and market equilibrium",
    specKeywords: [
      "demand",
      "supply",
      "price",
      "equilibrium",
      "surplus",
      "shortage",
      "market clearing",
    ],
  },
  {
    unitCode: "WEC11",
    unitTitle: CURRICULUM_UNITS.WEC11.title,
    topicCode: "1.3",
    topicTitle: "Elasticities",
    specKeywords: [
      "elasticity",
      "ped",
      "yed",
      "xed",
      "pes",
      "revenue",
      "burden",
    ],
  },
  {
    unitCode: "WEC11",
    unitTitle: CURRICULUM_UNITS.WEC11.title,
    topicCode: "1.4",
    topicTitle: "Market failure and government intervention",
    specKeywords: [
      "externality",
      "merit",
      "demerit",
      "public good",
      "information",
      "subsidy",
      "tax",
      "regulation",
      "carbon",
      "pollution",
    ],
  },
  {
    unitCode: "WEC12",
    unitTitle: CURRICULUM_UNITS.WEC12.title,
    topicCode: "2.1",
    topicTitle: "Aggregate demand and aggregate supply",
    specKeywords: [
      "aggregate demand",
      "aggregate supply",
      "ad",
      "as",
      "output gap",
      "recession",
      "boom",
    ],
  },
  {
    unitCode: "WEC12",
    unitTitle: CURRICULUM_UNITS.WEC12.title,
    topicCode: "2.2",
    topicTitle: "Economic growth, inflation, and unemployment",
    specKeywords: [
      "inflation",
      "cpi",
      "rpi",
      "unemployment",
      "employment",
      "wages",
      "growth",
      "gdp",
    ],
  },
  {
    unitCode: "WEC12",
    unitTitle: CURRICULUM_UNITS.WEC12.title,
    topicCode: "2.3",
    topicTitle: "Macroeconomic objectives and policy instruments",
    specKeywords: [
      "monetary policy",
      "fiscal policy",
      "interest rate",
      "bank of england",
      "fed",
      "ecb",
      "budget",
      "deficit",
      "debt",
      "quantitative easing",
    ],
  },
  {
    unitCode: "WEC12",
    unitTitle: CURRICULUM_UNITS.WEC12.title,
    topicCode: "2.4",
    topicTitle: "International and regional macroeconomic linkages",
    specKeywords: [
      "exchange rate",
      "currency",
      "depreciation",
      "appreciation",
      "balance of payments",
      "current account",
    ],
  },
  {
    unitCode: "WEC13",
    unitTitle: CURRICULUM_UNITS.WEC13.title,
    topicCode: "3.1",
    topicTitle: "Costs, revenues, and profits",
    specKeywords: [
      "profit",
      "revenue",
      "cost",
      "marginal cost",
      "average cost",
      "economies of scale",
    ],
  },
  {
    unitCode: "WEC13",
    unitTitle: CURRICULUM_UNITS.WEC13.title,
    topicCode: "3.2",
    topicTitle: "Market structures",
    specKeywords: [
      "monopoly",
      "oligopoly",
      "competition",
      "market power",
      "concentration",
      "merger",
    ],
  },
  {
    unitCode: "WEC13",
    unitTitle: CURRICULUM_UNITS.WEC13.title,
    topicCode: "3.3",
    topicTitle: "Labour markets",
    specKeywords: [
      "labour",
      "wage",
      "union",
      "migration",
      "skills",
      "minimum wage",
      "productivity",
    ],
  },
  {
    unitCode: "WEC14",
    unitTitle: CURRICULUM_UNITS.WEC14.title,
    topicCode: "4.1",
    topicTitle: "Globalisation and trade",
    specKeywords: [
      "trade",
      "tariff",
      "wto",
      "protectionism",
      "exports",
      "imports",
      "supply chain",
    ],
  },
  {
    unitCode: "WEC14",
    unitTitle: CURRICULUM_UNITS.WEC14.title,
    topicCode: "4.2",
    topicTitle: "Economic development and sustainability",
    specKeywords: [
      "development",
      "inequality",
      "poverty",
      "sustainability",
      "climate",
      "emerging",
    ],
  },
  {
    unitCode: "WEC14",
    unitTitle: CURRICULUM_UNITS.WEC14.title,
    topicCode: "4.3",
    topicTitle: "The financial sector",
    specKeywords: [
      "bank",
      "credit",
      "bond",
      "yield",
      "stock",
      "equity",
      "financial stability",
      "mortgage",
    ],
  },
];
